//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap car_green_east {
            get {
                object obj = ResourceManager.GetObject("car_green_east", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap car_green_west {
            get {
                object obj = ResourceManager.GetObject("car_green_west", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap car_grey_east {
            get {
                object obj = ResourceManager.GetObject("car_grey_east", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap car_grey_west {
            get {
                object obj = ResourceManager.GetObject("car_grey_west", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap car_yellow_east {
            get {
                object obj = ResourceManager.GetObject("car_yellow_east", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap car_yellow_west {
            get {
                object obj = ResourceManager.GetObject("car_yellow_west", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap checkbox_off {
            get {
                object obj = ResourceManager.GetObject("checkbox_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap checkbox_on {
            get {
                object obj = ResourceManager.GetObject("checkbox_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frogdead_drunk {
            get {
                object obj = ResourceManager.GetObject("frogdead_drunk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frogdead_east {
            get {
                object obj = ResourceManager.GetObject("frogdead_east", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap frogdead_west {
            get {
                object obj = ResourceManager.GetObject("frogdead_west", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] highscores {
            get {
                object obj = ResourceManager.GetObject("highscores", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap kikker_crazy {
            get {
                object obj = ResourceManager.GetObject("kikker_crazy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap kikker_east {
            get {
                object obj = ResourceManager.GetObject("kikker_east", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap kikker_west {
            get {
                object obj = ResourceManager.GetObject("kikker_west", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap level_navigate_right {
            get {
                object obj = ResourceManager.GetObject("level_navigate_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap level_navigate_selected_right {
            get {
                object obj = ResourceManager.GetObject("level_navigate_selected_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap live {
            get {
                object obj = ResourceManager.GetObject("live", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_frogger_reloaded {
            get {
                object obj = ResourceManager.GetObject("logo_frogger_reloaded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static byte[] lvl_basic1 {
            get {
                object obj = ResourceManager.GetObject("lvl_basic1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] lvl_basic2 {
            get {
                object obj = ResourceManager.GetObject("lvl_basic2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] lvl_basic3 {
            get {
                object obj = ResourceManager.GetObject("lvl_basic3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] lvl_coolroad {
            get {
                object obj = ResourceManager.GetObject("lvl_coolroad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] lvl_highway {
            get {
                object obj = ResourceManager.GetObject("lvl_highway", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] lvl_sea {
            get {
                object obj = ResourceManager.GetObject("lvl_sea", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap selecteditem {
            get {
                object obj = ResourceManager.GetObject("selecteditem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap texure_grass {
            get {
                object obj = ResourceManager.GetObject("texure_grass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap treetrunk {
            get {
                object obj = ResourceManager.GetObject("treetrunk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap truck_east {
            get {
                object obj = ResourceManager.GetObject("truck_east", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap truck_west {
            get {
                object obj = ResourceManager.GetObject("truck_west", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
